import type { ReferenceEntry } from "@/lib/references/types";

export const referenceDatabase: ReferenceEntry[] = [
  {
    id: "therme-vals",
    slug: "therme-vals",
    type: "building",
    title: "Therme Vals",
    creatorIds: ["peter-zumthor"],
    year: 1996,
    location: "Vals, Switzerland",
    buildingTypes: ["bath", "spa", "public interior"],
    applicableScales: ["detail", "room", "building", "site"],
    overview:
      "A thermal bath known for its spatial sequence, stone construction, light, water, and bodily atmosphere.",
    designIntent:
      "Make bathing feel embedded in stone, temperature, sound, and a slow sequence of rooms.",
    problemsAddressed: ["atmosphere", "sensory experience", "material presence"],
    strategies: ["sequential rooms", "heavy material", "controlled light"],
    themes: ["atmosphere", "material", "water", "sequence"],
    spatialCharacteristics: ["compressed passages", "varied bathing rooms"],
    circulationStrategies: ["slow wandering sequence", "thresholds"],
    structuralStrategies: ["massive stone-like enclosure"],
    materialStrategies: ["stone", "water", "precise joints"],
    environmentalStrategies: ["thermal experience", "light modulation"],
    urbanStrategies: ["embedded site relationship"],
    lessons: [
      "Atmosphere can be tested through section, material, and bodily sequence.",
    ],
    risksOfMisapplication: [
      "Copying darkness, stone, or mood without the construction logic will flatten the lesson.",
    ],
    relevantProjectStages: ["concept", "schematic-design", "design-development"],
    sourceIds: ["zumthor-atmospheres", "zumthor-thinking-architecture"],
  },
  {
    id: "bruder-klaus-field-chapel",
    slug: "bruder-klaus-field-chapel",
    type: "building",
    title: "Bruder Klaus Field Chapel",
    creatorIds: ["peter-zumthor"],
    year: 2007,
    location: "Mechernich, Germany",
    buildingTypes: ["chapel", "memorial", "small sacred space"],
    applicableScales: ["detail", "room", "building", "site"],
    overview:
      "A small chapel where construction process, interior darkness, light, and material memory are central.",
    designIntent:
      "Create a focused sacred interior through material process, compression, and an opening to the sky.",
    problemsAddressed: ["sacred atmosphere", "material process", "interior focus"],
    strategies: ["single intense room", "process-driven material", "controlled aperture"],
    themes: ["memory", "material", "light", "silence"],
    spatialCharacteristics: ["single vertical interior", "thick enclosure"],
    circulationStrategies: ["direct threshold", "compressed entry"],
    structuralStrategies: ["monolithic enclosure"],
    materialStrategies: ["concrete", "charred formwork trace"],
    environmentalStrategies: ["sky aperture", "darkness and light"],
    urbanStrategies: ["rural landmark"],
    lessons: ["Construction process can become spatial and atmospheric evidence."],
    risksOfMisapplication: ["A dramatic material effect is not enough without ritual and spatial clarity."],
    relevantProjectStages: ["concept", "schematic-design", "design-development"],
    sourceIds: ["zumthor-atmospheres"],
  },
  {
    id: "seattle-central-library",
    slug: "seattle-central-library",
    type: "building",
    title: "Seattle Central Library",
    creatorIds: ["rem-koolhaas"],
    year: 2004,
    location: "Seattle, United States",
    buildingTypes: ["library", "civic building"],
    applicableScales: ["room", "building", "site", "city"],
    overview:
      "A civic library organized through programmatic platforms, circulation, and a public urban role.",
    designIntent:
      "Reorganize the library around contemporary media, public access, and differentiated programmatic zones.",
    problemsAddressed: ["program complexity", "public institution", "circulation"],
    strategies: ["program platforms", "continuous circulation", "urban visibility"],
    themes: ["program", "publicness", "infrastructure", "event"],
    spatialCharacteristics: ["stacked zones", "large public interiors"],
    circulationStrategies: ["legible public route", "vertical connections"],
    structuralStrategies: ["large-span enclosure"],
    materialStrategies: ["glass and steel envelope"],
    environmentalStrategies: ["daylit public rooms"],
    urbanStrategies: ["downtown civic presence"],
    lessons: ["Program can be the main generator of building form and experience."],
    risksOfMisapplication: ["A complex diagram should not be copied without operational program logic."],
    relevantProjectStages: ["concept", "schematic-design", "design-development"],
    sourceIds: ["oma-smlxl", "moma-project-records"],
  },
  {
    id: "kunsthal-rotterdam",
    slug: "kunsthal-rotterdam",
    type: "building",
    title: "Kunsthal Rotterdam",
    creatorIds: ["rem-koolhaas"],
    year: 1992,
    location: "Rotterdam, Netherlands",
    buildingTypes: ["museum", "exhibition hall"],
    applicableScales: ["room", "building", "site"],
    overview:
      "An exhibition building known for overlapping routes, ramps, and programmatic crossings.",
    designIntent:
      "Use circulation and section to connect exhibition, public movement, and site conditions.",
    problemsAddressed: ["circulation", "program overlap", "site connection"],
    strategies: ["ramps", "crossing routes", "sectional organization"],
    themes: ["movement", "program", "event", "section"],
    spatialCharacteristics: ["intersecting volumes", "varied gallery conditions"],
    circulationStrategies: ["ramps", "crossing paths"],
    structuralStrategies: ["mixed structural systems"],
    materialStrategies: ["industrial palette"],
    environmentalStrategies: ["varied light conditions"],
    urbanStrategies: ["park and street connection"],
    lessons: ["Circulation can become the main site-program mediator."],
    risksOfMisapplication: ["Route complexity without a public logic can become confusion."],
    relevantProjectStages: ["concept", "schematic-design"],
    sourceIds: ["oma-smlxl"],
  },
  {
    id: "salk-institute",
    slug: "salk-institute",
    type: "building",
    title: "Salk Institute",
    creatorIds: ["louis-kahn"],
    year: 1965,
    location: "La Jolla, United States",
    buildingTypes: ["research institute", "laboratory", "campus"],
    applicableScales: ["room", "building", "site"],
    overview:
      "A research campus known for its courtyard, laboratory order, service organization, and relationship to horizon and light.",
    designIntent:
      "Give scientific work an ordered institutional setting with strong served and servant organization.",
    problemsAddressed: ["institutional order", "laboratory organization", "structure"],
    strategies: ["served and servant hierarchy", "courtyard", "structural clarity"],
    themes: ["order", "light", "institution", "structure"],
    spatialCharacteristics: ["paired laboratory blocks", "central court"],
    circulationStrategies: ["clear axial movement", "service separation"],
    structuralStrategies: ["integrated structural bays"],
    materialStrategies: ["concrete", "wood", "durable surfaces"],
    environmentalStrategies: ["light and horizon orientation"],
    urbanStrategies: ["campus edge condition"],
    lessons: ["Institutional clarity can come from structure, service, and open space working together."],
    risksOfMisapplication: ["Monumentality without service logic can become empty symmetry."],
    relevantProjectStages: ["concept", "schematic-design", "design-development"],
    sourceIds: ["kahn-writings-lectures-interviews"],
  },
  {
    id: "kimbell-art-museum",
    slug: "kimbell-art-museum",
    type: "building",
    title: "Kimbell Art Museum",
    creatorIds: ["louis-kahn"],
    year: 1972,
    location: "Fort Worth, United States",
    buildingTypes: ["museum"],
    applicableScales: ["detail", "room", "building"],
    overview:
      "A museum known for repeated vaulted rooms, controlled daylight, and structural-spatial clarity.",
    designIntent:
      "Create calm gallery rooms where structure and daylight define the viewing experience.",
    problemsAddressed: ["gallery light", "room order", "structure"],
    strategies: ["repeated room module", "daylight control", "structural rhythm"],
    themes: ["room", "light", "order", "museum"],
    spatialCharacteristics: ["vaulted gallery rooms", "modular order"],
    circulationStrategies: ["clear room-to-room sequence"],
    structuralStrategies: ["vaulted roof modules"],
    materialStrategies: ["concrete", "travertine", "light reflectors"],
    environmentalStrategies: ["controlled daylight"],
    urbanStrategies: ["low civic presence"],
    lessons: ["Light can be a spatial ordering system rather than an effect.",
    ],
    risksOfMisapplication: ["Repeating a vault shape without light logic misses the architectural lesson."],
    relevantProjectStages: ["schematic-design", "design-development", "final-review"],
    sourceIds: ["kahn-writings-lectures-interviews"],
  },
  {
    id: "greenwich-village",
    slug: "greenwich-village",
    type: "urban-case",
    title: "Greenwich Village",
    creatorIds: ["jane-jacobs"],
    location: "New York, United States",
    buildingTypes: ["neighborhood", "mixed-use urban fabric"],
    applicableScales: ["site", "city"],
    overview:
      "An urban case associated with Jacobs's observations on mixed use, street life, density, and everyday public safety.",
    designIntent:
      "Not an authored design project; useful as an observed urban condition for studying everyday life.",
    problemsAddressed: ["street life", "mixed use", "public safety", "urban diversity"],
    strategies: ["mixed uses", "short blocks", "active edges", "time diversity"],
    themes: ["public life", "street", "users", "adaptation"],
    spatialCharacteristics: ["fine-grain blocks", "active ground floors"],
    circulationStrategies: ["walkable network", "multiple paths"],
    structuralStrategies: [],
    materialStrategies: [],
    environmentalStrategies: [],
    urbanStrategies: ["mixed use", "street observation", "small-grain diversity"],
    lessons: ["Publicness should be checked against real occupation and time patterns."],
    risksOfMisapplication: ["Do not treat Jacobs's observations as a style or as proof that any dense street is successful."],
    relevantProjectStages: ["concept", "schematic-design", "final-review"],
    sourceIds: ["jacobs-death-and-life"],
  },
  {
    id: "washington-square-park",
    slug: "washington-square-park",
    type: "urban-case",
    title: "Washington Square Park",
    creatorIds: ["jane-jacobs"],
    location: "New York, United States",
    buildingTypes: ["park", "public space", "urban case"],
    applicableScales: ["site", "city"],
    overview:
      "A public-space urban case useful for studying edges, users, conflict, and daily occupation.",
    designIntent:
      "Not an authored Jacobs project; useful as a case for understanding how public life is sustained.",
    problemsAddressed: ["publicness", "users", "urban edges", "daily patterns"],
    strategies: ["active edges", "multiple user groups", "porous access"],
    themes: ["public space", "occupation", "street life"],
    spatialCharacteristics: ["central public open space", "edge conditions"],
    circulationStrategies: ["crossing routes", "porous entries"],
    structuralStrategies: [],
    materialStrategies: [],
    environmentalStrategies: ["shade and open space"],
    urbanStrategies: ["adjacent mixed urban fabric"],
    lessons: ["Open space needs users, edges, and daily rhythms to become public.",
    ],
    risksOfMisapplication: ["A plaza is not public simply because it is open or visually iconic."],
    relevantProjectStages: ["concept", "schematic-design", "final-review"],
    sourceIds: ["jacobs-death-and-life"],
  },
  {
    id: "villa-savoye",
    slug: "villa-savoye",
    type: "building",
    title: "Villa Savoye",
    creatorIds: ["le-corbusier"],
    year: 1931,
    location: "Poissy, France",
    buildingTypes: ["house", "villa"],
    applicableScales: ["room", "building", "site"],
    overview:
      "A canonical modern house associated with promenade, free plan, pilotis, roof garden, and object-site relation.",
    designIntent:
      "Organize modern living through movement, proportion, structural separation, and elevated relation to site.",
    problemsAddressed: ["modern living", "promenade", "plan order"],
    strategies: ["pilotis", "ramp promenade", "roof landscape", "free plan"],
    themes: ["promenade", "proportion", "light", "modern order"],
    spatialCharacteristics: ["elevated volume", "free plan", "roof terrace"],
    circulationStrategies: ["ramp sequence", "processional movement"],
    structuralStrategies: ["pilotis and frame"],
    materialStrategies: ["white rendered surfaces", "modern industrial character"],
    environmentalStrategies: ["roof garden", "horizontal windows"],
    urbanStrategies: ["object in landscape"],
    lessons: ["Circulation can unfold the architectural argument over time."],
    risksOfMisapplication: ["Borrowing the Five Points without programmatic reason becomes stylistic quotation."],
    relevantProjectStages: ["concept", "schematic-design", "design-development"],
    sourceIds: ["le-corbusier-towards-new-architecture", "le-corbusier-oeuvre-complete"],
  },
  {
    id: "ronchamp",
    slug: "ronchamp",
    type: "building",
    title: "Notre-Dame du Haut",
    creatorIds: ["le-corbusier"],
    year: 1955,
    location: "Ronchamp, France",
    buildingTypes: ["chapel", "sacred space"],
    applicableScales: ["room", "building", "site"],
    overview:
      "A chapel known for plastic form, thick walls, controlled light, and strong site presence.",
    designIntent:
      "Create a powerful sacred place through mass, light, acoustic enclosure, and hilltop presence.",
    problemsAddressed: ["sacred space", "light", "site presence"],
    strategies: ["thick walls", "controlled apertures", "expressive roof"],
    themes: ["light", "form", "site", "spiritual experience"],
    spatialCharacteristics: ["irregular chapel interior", "thick enclosure"],
    circulationStrategies: ["pilgrimage approach", "threshold sequence"],
    structuralStrategies: ["expressive roof and wall system"],
    materialStrategies: ["white wall surfaces", "massive enclosure"],
    environmentalStrategies: ["punctured daylight", "acoustic enclosure"],
    urbanStrategies: ["hilltop landmark"],
    lessons: ["Form can be judged by how it shapes light, ritual, and site experience."],
    risksOfMisapplication: ["Expressive form without spatial necessity becomes arbitrary sculpture."],
    relevantProjectStages: ["concept", "schematic-design", "design-development"],
    sourceIds: ["le-corbusier-oeuvre-complete"],
  },
];
