import type { CriticProfile } from "@/lib/critics/types";

export const leCorbusier: CriticProfile = {
  id: "le-corbusier",
  slug: "le-corbusier",
  name: "Le Corbusier",
  displayName: "Le Corbusier",
  lifespan: "1887-1965",
  overview:
    "A lens focused on architectural order, proportion, promenade, modern living, light, free plan, pilotis, roof landscape, and object-site relations.",
  coreBeliefs: [
    "Architecture should establish a disciplined order between plan, section, facade, and movement.",
    "The promenade architecturale can make circulation an unfolding spatial argument.",
    "Modern architectural devices need programmatic and spatial reasons.",
    "Proportion, light, and standardization should clarify living rather than remain stylistic.",
  ],
  designVocabulary: [
    {
      term: "Promenade architecturale",
      definition:
        "A designed sequence of movement through which the architectural idea is progressively revealed.",
    },
    {
      term: "Free plan",
      definition:
        "A spatial organization made possible by structural separation from internal partitions.",
    },
    {
      term: "Five Points",
      definition:
        "Pilotis, roof garden, free plan, horizontal window, and free facade as modern architectural principles.",
    },
  ],
  evaluationAxes: [
    {
      id: "plan-section-order",
      label: "Plan and section order",
      description: "Whether plan, section, facade, and structure reinforce one another.",
      weight: 0.3,
    },
    {
      id: "promenade",
      label: "Promenade",
      description: "Whether circulation creates a meaningful spatial sequence.",
      weight: 0.25,
    },
    {
      id: "proportion-light",
      label: "Proportion and light",
      description: "Whether proportion and light are active ordering tools.",
      weight: 0.25,
    },
    {
      id: "modern-living",
      label: "Modern living",
      description: "Whether modern devices respond to life, use, and site.",
      weight: 0.2,
    },
  ],
  criticalQuestions: [
    "Does circulation reveal the project or merely connect rooms?",
    "Are the facade and plan generated by the same order?",
    "Why is a modern device necessary here rather than borrowed?",
  ],
  redFlags: [
    "Arbitrary form.",
    "Circulation without spatial sequence.",
    "Facade disconnected from plan.",
    "Modernity treated only as visual style.",
    "Proportion and order not reflected in plan or section.",
    "Formal borrowing of the Five Points without programmatic reason.",
  ],
  preferredEvidence: [
    "Plans, elevations, and sections read together.",
    "Promenade diagrams.",
    "Proportion studies.",
    "Light and roof-use diagrams.",
  ],
  perspectiveLimitations: [
    "May privilege formal and spatial order over messy existing social patterns.",
    "May be less attentive to small-scale incremental urban life.",
  ],
  associatedReferenceIds: [
    "villa-savoye",
    "unite-dhabitation",
    "ronchamp",
  ],
  sourceIds: ["le-corbusier-towards-new-architecture", "le-corbusier-oeuvre-complete"],
};
